apiVersion: apps/v1
kind: Deployment
metadata:
  name: ku-it-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ku-it
  template:
    metadata:
      labels:
        app: ku-it
    spec:
      containers:
      - name: assistant
        image: docker.io/sayan896/ku-it-assistant:d3e2324c9bb901144fd6bbab44bb8e3667191f0f
        ports:
        - containerPort: 80
