apiVersion: apps/v1
kind: Deployment
metadata:
  name: ku-it-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ku-it
  template:
    metadata:
      labels:
        app: ku-it
    spec:
      containers:
      - name: assistant
        image: docker.io/sayan896/ku-it-assistant:e17c9b87d50d2340fe01b239e0b1ecdf917e0e17
        ports:
        - containerPort: 80
