name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm prune --production

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
    
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_REGISTRY }}/ku-it-assistant:${{ github.sha }}
          file: Dockerfile
          build-args: |
            REACT_APP_HF_API_KEY=${{ secrets.REACT_APP_HF_API_KEY }}
      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_KEY }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/ku-it-assistant:${{ github.sha }}

  trivy-scan:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_REGISTRY }}/ku-it-assistant:${{ github.sha }}

  k8s-manifest:
    needs: trivy-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate Kubernetes manifest
        run: |
          mkdir -p deployment
          cat <<EOF > deployment/kubernetes.yml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ku-it-assistant
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: ku-it
            template:
              metadata:
                labels:
                  app: ku-it
              spec:
                containers:
                - name: assistant
                  image: ${{ secrets.DOCKER_REGISTRY }}/ku-it-assistant:${{ github.sha }}
                  ports:
                  - containerPort: 80
          EOF

      - name: Commit and push manifest to repo
        run: |
          git add deployment/kubernetes.yml
          git commit -m "Update k8s manifest for ${{ github.sha }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

